version: '2'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./customerapp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - customerapp-net

networks:
  customerapp-net:
    driver: "bridge"
